all:	main.cpp ../controle/ControleAluno.cpp ../modelo/persistencia/DAOAluno.cpp ../modelo/entidade/Aluno.cpp  ../controle/ControleProfessor.cpp ../modelo/persistencia/DAOProfessor.cpp ../modelo/entidade/Professor.cpp ../controle/ControleTurma.cpp ../modelo/persistencia/DAOTurma.cpp ../modelo/entidade/Turma.cpp
	g++ main.cpp -o EXEC ../controle/ControleTurma.cpp ../modelo/persistencia/DAOTurma.cpp ../modelo/entidade/Turma.cpp ../controle/ControleProfessor.cpp ../modelo/persistencia/DAOProfessor.cpp ../modelo/entidade/Professor.cpp ../controle/ControleAluno.cpp ../modelo/persistencia/DAOAluno.cpp ../modelo/entidade/Aluno.cpp


